#!/bin/bash
# Copyright (c) 2014 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# PROPRIETARY/CONFIDENTIAL
#
# Use is subject to license terms.

IDME_PARTITION="/dev/disk/by-partlabel/idme"
MOUNT_POINT="/var/volatile/tmp/idme"

(
    set -x

    echo "Force unmounting of IDME partition ${MOUNT_POINT}"
    /bin/umount $MOUNT_POINT || /bin/umount -f $MOUNT_POINT

    echo "Format ${IDME_PARTITION} ext3"
    /sbin/mkfs.ext3 -j $IDME_PARTITION

    echo "Forcing an emergency reboot"
    /bin/sync
    /sbin/reboot -d -f

) 2>&1 | /usr/bin/logger -t idme_recovery
